# Введение в машинное обучение

## Основы работы в Python

Прежде чем начать работать и писать код стоит удостовериться, что вы подключили все необходимые вам библиотеки. Делается это с помощью команды import NAME или from NAME1 import NAME2, для сокращения можно использовать as

In [2]:
import numpy as np
import pandas as pd
import scipy as sc
import sklearn as sk
from matplotlib import pylab as plt

Python обладает потрясающим количеством библиотек и расширений, которые сильно упрощают написание кода. Многие алгоритмы и функции вы можете найти в пакетах выше. Для начала стоит ознакомиться с типами данных в Python. Списки (lists), кортежи (tuples), множества (sets), словари (dictionaries) предоставляют огромные возможности.

In [3]:
a = (1,2,3,4)
type(a)

tuple

In [4]:
b = [1,2,3,4]
type(b)

list

In [5]:
c = {"a":1, "b":2}
type(c)

dict

In [6]:
d={1,2,3,3,4}
type(d)

set

In [92]:
d.add(1)
d

{1}

Ознакомьтесь с основными функциями, которые предоставляют вам эти типы. Обратите внимание, что они бывают изменяемыми и неизменяемыми, хешируемыми и нет. Почитайте описание и попробуйте использование следующих функций: append(), insert(), delete(), remove(), len(). 

In [25]:
b.append(7)
b

[1, 2, 3, 4, 7, 7]

In [29]:
b.insert(0,5)
b

[5, 5, 1, 2, 3, 4, 7, 7]

In [35]:
len(c)

2

In [51]:
del(b[1])

In [52]:
b

[5, 3, 4, 7, 7]

In [56]:
b.remove(4)
b

[5, 7, 7]

Списки очень мощный встроенный тип. Они могут содержать в себе любые другие типы, и позволяют делать срезы с помощью простого синтаксиса. 

In [8]:
aa=[a,2.5,3,[1,2],(3,4),"abc",True,False,1e10,3+2j,{1,23},{3:"as"},{("aas"):"bc"}]
type(aa)
aa[0]

(1, 2, 3, 4)

Cрезы делаются на основе индексов. Индексы нумеруются с нуля. Первый индекс включается в перечисление, последний нет.

In [9]:
aa[0:5]

[(1, 2, 3, 4), 2.5, 3, [1, 2], (3, 4)]

In [10]:
aa[3:8]

[[1, 2], (3, 4), 'abc', True, False]

Срез можно начинать с ":"

In [11]:
aa[:11]

[(1, 2, 3, 4),
 2.5,
 3,
 [1, 2],
 (3, 4),
 'abc',
 True,
 False,
 10000000000.0,
 (3+2j),
 {1, 23}]

In [12]:
aa[2:]

[3,
 [1, 2],
 (3, 4),
 'abc',
 True,
 False,
 10000000000.0,
 (3+2j),
 {1, 23},
 {3: 'as'},
 {'aas': 'bc'}]

Можно отсчитывать индексы в обратную сторону.

In [13]:
aa[-1]

{'aas': 'bc'}

In [14]:
aa[-3:-1]

[{1, 23}, {3: 'as'}]

In [22]:
aa[-3:2] #Почему вернулся пустой список?

[]

При этом второе число - индекс последнего элемента до которого будет срез. Т.к. 2>(-3) - получили пустой список, чтобы получить срез нужно вместо (2) -> -(n-1)/ где n-число элементов. 
Мы начали использовать обратные индесы - надо использовать везде(и старт и стоп)

In [18]:
#Потренируйтесь на срезах, и складывать\вычитать списки с помощью + и -. Попробуйте другие операторы.

In [75]:
A = np.array([1,2,3,4,5])
B = [1,2,3,4,5]
C = np.array([4,3,2,1,6])
print(A*2)
print(B*2)
print(A+B)
print(type(B+A))
print(B+[1])
print(A-C)

[ 2  4  6  8 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 1]
[-3 -1  1  3 -1]


In [82]:
#Выясните разницу между списками, кортежами, множествами.

tuple - неизменяемый кортеж элеметов. мы не можем изменить его элементы каким-либо образом
list - возможно все, помимо того, что доступно для tuple добавляется возможность изменения элеметов(изменение значения, удаление или добавление внутрь списка нового элемета). В tuple добавление только в конце
set - мнодество, в нем нет повторяющихся элементов. Элементы его не имеют индексов. Доступно добавление элемента и удаление. (discard("specific 'elemet") 

In [93]:
a+a

(1, 2, 3, 4, 1, 2, 3, 4)

In [94]:
a[1]

2

In [95]:
a[1]=0

TypeError: 'tuple' object does not support item assignment

In [96]:
b+b

[5, 7, 7, 5, 7, 7]

In [104]:
b[0]=3
b[1:3] = [7,6,5,7]
print(b)
b.pop(1)
b.remove(3)
b

[3, 7, 6, 5, 7, 7, 7, 7, 7, 5, 7, 5, 7]


[6, 5, 7, 7, 7, 7, 7, 5, 7, 5, 7]

In [106]:
d = {1,2,3,4,5}
d[1]

TypeError: 'set' object is not subscriptable

In [110]:
d.pop()
d

{4, 5}

In [112]:
d.discard(5)
d

{4}

Python один из лучших языков для работы с текстом. Строки в python это последовательности символов, к ним можно применять синтаксис срезов.

In [34]:
x = "Hello"
y = " world"
print(x+y)

Hello world


In [37]:
x[1:4]

'ell'

In [ ]:
#Изучите методы rstrip, lstrip, strip, lower, upper, join, split, replace, list, str, int

In [120]:
some_text = "long way"
some_text.split(" ")

['long', 'way']

In [124]:
some_text.join("431")

'4long way3long way1'

In [125]:
some_text

'long way'

In [126]:
some_text.replace("l", "L")

'Long way'

In [128]:
list(some_text)

['l', 'o', 'n', 'g', ' ', 'w', 'a', 'y']

In [130]:
new_txt = "12345"
print(type(new_txt))
type(int(new_txt))

<class 'str'>


int

In [135]:
print(some_text.rstrip('y'))
print(some_text.lstrip('lo'))
txt = '1234lomd-dfd;lfskd11'
print(txt.strip('1'))

long wa
ng way
234lomd-dfd;lfskd


In [38]:
print("%s is scattered on %s through %s exchange" % ("neutrino","electron","Z-boson"))

neutrino is scattered on electron through Z-boson exchange


In [137]:
#Обратите внимание на модуль import re
#пример кода(не будет работать, т.к нет в папке файлов)
'''for fl in os.listdir():
    if re.match(r'.*[2][1-6]', fl):
        if len(dataset)==0:
            dataset=[np.genfromtxt((fl),delimiter = ',')[10:16]]
        else:
            dataset=np.append(dataset,([np.genfromtxt((fl),delimiter = ',')[10:16]]),axis = 0)
dataset = np.mean(dataset.reshape(dataset.shape[0],dataset.shape[1],-1,20),3)'''
#суть - у меня есть файлы с набором данных,
#я хочу рассмотреть определенные файлы и для этого делаю отбор файлов по именам с помощью шаблона

"for fl in os.listdir():\n    if re.match(r'.*[2][1-6]', fl):\n        if len(dataset)==0:\n            dataset=[np.genfromtxt((fl),delimiter = ',')[10:16]]\n        else:\n            dataset=np.append(dataset,([np.genfromtxt((fl),delimiter = ',')[10:16]]),axis = 0)\ndataset = np.mean(dataset.reshape(dataset.shape[0],dataset.shape[1],-1,20),3)"

Управляющие конструкции реализованы стандартным набором условий и циклов. Обратите внимание на логические операторы and, not, or и на операторы сравнения is, is not, in, not in. Роль фигурных скобок из С здесь играют отступы, 4 пробела или табуляция по договоренности.

In [138]:
x=5 #Можно ли изменить x так, чтобы вывести слово "done"?
if x>5:
    for i in range(6):
        x-=1
        print(x)
elif x<5:
    x-=2
    print(x)
else:
    print("done")

done


In [14]:
#поэскпериментируйте с range(), и циклом for. что будет если использовать спискок вместо range? Изучите цикл while самостоятельно

In [140]:
x = 7
if x>5:
    for i in [1,2,3,4]:
        x-=1
        print(x)
elif x<5:
    x-=2
    print(x)
else:
    print("done")

6
5
4
3


In [143]:
x = 7
while(True):
    x-=1
    if x == 0:
        break
print(x)

0


Функции неотъемлемая часть Python. Ключевое слово def(). Важной является работа с аргументами.

In [15]:
def func():
    pass

In [16]:
def func1():
    return 0
func1()

0

In [22]:
def func2(x,y):
    print("sum is: ")
    return x+y
func2(1,1)

sum is: 


2

In [146]:
def func3(x,y=1,z=2,*tup):
    print((x,y,z)+tup)
func3(1,3,4,5,6) #поэскпериментируйте здесь

(1, 3, 4, 5, 6)


In [25]:
def func4(x,y,z=1, **kwargs):
    print(x,y,z,kwargs)
func4(1,2,m=5,n=3,z=3)

1 2 3 {'m': 5, 'n': 3}


In [26]:
#в чем принципиальная разница в результате работы между func3 и func4?
#реализуйте функцию,вычисляющую факториал с помощью рекурсии
#func3 - заданы 2 параметра по умлочанию, 
#и есть возможность передать список переменных неопределенной длины(без названия)
#func4 - задан 1 параметр по ум., есть возможность передать функции
#список аргументов с ключевыми словами(с обознчением переменных)

In [148]:
#в результате работы func3 к списку аргументов обозначеных явно, добавляется список из арг *tup
#в результате работы func4 к списку аргументов добавляется словарь переданных параметров, где ключи - написанные нами переменные.


Рассмотрите самостоятельно следующие темы: исключения, модули. Напишите функцию факториала в отдельный модуль.

In [158]:
def fact(numb):
    if numb<0:
        return 0
    if numb==0:
        return 1
    else:
        return numb*(fact(numb-1))
    
print(fact(-5))

try:
    fact(a)
except TypeError:
    print("NO!")
    

0
NO!


Python поддерживает парадигму ООП. Прочитайте про классы, методы и наследование.

In [32]:
class Shape:
    def __init__(self,x,y): #Что такое __init__ -> аналог конструктора в C++, позволяет при создании объекта задавать ему некие параметры и пр.
        self.x=x
        self.y=y
    def move(self,dx,dy):
        self.x = self.x + dx
        self.y = self.y + dy
        print("Rolling!")
        
class Square(Shape):
    def __init__(self,side_length=1,x=0,y=0):
        Shape.__init__(self,x,y)
        self.side_length = side_length
        
sq = Square(1,2,3)
print(sq.x,sq.y)

sq.move(1,3)
print(sq.x,sq.y)

2 3
Rolling!
3 6


In [10]:
#Создайте класс Particle, у которой будут такие аттрибуты как заряд, масса и др. 
#Также придумайте методы, которые реализуют взаимодействие.
class Particle: 
    def __init__(self,charge=0,mass=0,decaytime=0,name='',E=0):
        self.name = name
        self.charge = charge
        self.mass = mass
        self.decaytime = decaytime
        self.en = E
    def interaction(self,other):#абсолютный рандом.
        return self.en*other.en
    

In [11]:
p1 = Particle(1,2,name = "p", E = 6.6)

In [12]:
p2 = Particle(2,3,name = "n", E = 10)

In [13]:
p2.interaction(p1)

66.0